### ISSUE TITLE
client.on doesn't get server.send message

### ISSUE THREAD

**Issue by kobimx** [marcbachmann/electron-rpc#3]
I'm trying to send a message from the main process to the client (webContents), but the client doesn't receive the message sent and it doesn't trigger the callback. server.configure is set and doesn't give errors. it's strange because if i use `webContents.send(channel[, arg1][, arg2][, ...])` the standard method it works so i thought it's was an `electron-rpc` bug, or i'm just doing something wrong :/

**Comment by marcbachmann** [comment]
Do you have some code so I can reproduce it?

**Comment by kobimx** [comment]
I'm using the [menubar](https://github.com/maxogden/menubar) module to create an app and needed to send some messages from the main to the renderer. here's some snippets of the code
mains.js

``` javascript
var menubar = require('menubar');
var Server = require('electron-rpc/server');
var serv = new Server();
var mb = menubar({"preloadWindow": true, "width": 300, "height": 130});
...
mb.on('after-hide', function() {
    console.log("sending hide");
    serv.send('hideLoadIndex'); //doesn't work
    mb.window.webContents.send("hideLoadIndex"); //works
});
```

renderer's js

``` javascript
var Client = require('electron-rpc/client');
var client = new Client();
...
require('electron').ipcRenderer.on('hideLoadIndex', function() { //works
    if(settingLoaded) {
        $("body").load("./app/index.tmpl");
        settingLoaded = false;
    } 
});

client.on('hideLoadIndex', function() { //doesn't work
       if(settingLoaded) {
        $("body").load("./app/index.tmpl");
        settingLoaded = false;
    } 
});
```

I do use `serv.configure(mb.window.webContents);`

**Comment by ningt** [comment]
I have the same problem and I am using electron-rpc@2.0.0

**Comment by ghost** [comment]
https://github.com/marcbachmann/electron-rpc/blob/master/client.js#L42
`function responseMessageHandler (response) {` 
=> 
`function responseMessageHandler (e, response) {`

**Comment by marcbachmann** [comment]
Thanks for debugging that. sorry, that this lib doesn't have a test yet. was somewhat a prototype.
Does somebody of you have a proper electron test setup?

**Comment by marcbachmann** [comment]
I've fixed that. Please try v2.0.1

**Comment by kobimx** [comment]
It works now, GJ!
